/*
 * SelectFich.java
 *
 * Created on 23 avril 2007, 11:26
 */

package selectfich;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author  Moonesh.Ramburrun
 */
public class SelectFich extends javax.swing.JFrame {
    
    /** Creates new form SelectFich */
    public SelectFich() {
        initComponents();
        listModel = new javax.swing.DefaultListModel<>( ); 
        jList1.setModel(listModel); 
// on fera jList1.setListData(listModel.toArray()); directement pour un obj de type ArrayList
        setLocation(200,150);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionnerFichier = new javax.swing.JButton();
        editerFichier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        calculerMoyenne = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                S E L E C T I O N     D ' U N    F I C H I E R    T E X T E  ");

        selectionnerFichier.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        selectionnerFichier.setText("Sélectionner un fichier texte");
        selectionnerFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionnerFichierActionPerformed(evt);
            }
        });

        editerFichier.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        editerFichier.setText("Editer Le Fichier Des Notes");
        editerFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editerFichierActionPerformed(evt);
            }
        });

        jList1.setBackground(new java.awt.Color(102, 204, 255));
        jList1.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFocusable(false);
        jScrollPane1.setViewportView(jList1);

        calculerMoyenne.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        calculerMoyenne.setText("Calculer moyennes et Ecort Types");
        calculerMoyenne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculerMoyenneActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom-Prenom");

        jLabel2.setText("Note 1");

        jLabel3.setText("Note 2");

        jLabel4.setText("Moy Etu");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(calculerMoyenne, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(editerFichier, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(selectionnerFichier, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(24, 24, 24))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(84, 84, 84)
                        .add(jLabel2)
                        .add(38, 38, 38)
                        .add(jLabel3)
                        .add(38, 38, 38)
                        .add(jLabel4)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(jLabel3)
                    .add(jLabel2)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(selectionnerFichier)
                        .add(43, 43, 43)
                        .add(editerFichier)
                        .add(41, 41, 41)
                        .add(calculerMoyenne))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 240, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectionnerFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionnerFichierActionPerformed
     javax.swing.JFileChooser bdd;
     bdd = new javax.swing.JFileChooser( new java.io.File(".") );
     Filtre f;
     f = new Filtre();
     bdd.addChoosableFileFilter(f); // filtre à appliquer
     bdd.setFileFilter(f);
     if( bdd.showOpenDialog(null) == javax.swing.JFileChooser.APPROVE_OPTION ){
      // bdd.showSaveDialog pour la boîte de dialogue de sauvegarde
      fichier = bdd.getSelectedFile();
     } 
     if ( fichier == null ){ 
      javax.swing.JOptionPane.showMessageDialog(
              this,
              "Vous n'avez pas selectionné un nom de fichier : \"noms.txt\" choisi par défaut )" );
     }
     else{
      fichierSelectionne =  fichier.getName();
     }             
    }//GEN-LAST:event_selectionnerFichierActionPerformed

    private void editerFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editerFichierActionPerformed
     if ( fichier == null )
     { 
       javax.swing.JOptionPane.showMessageDialog( this, "Vous n'avez pas selectionné un nom de fichier " );
      
     }
     
     try
     {
       java.awt.Desktop.getDesktop().edit(fichier);
     }
     catch ( java.io.IOException e ) { 
       javax.swing.JOptionPane.showMessageDialog( this, e.getMessage() );
     } 
     
    }//GEN-LAST:event_editerFichierActionPerformed

    private void calculerMoyenneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculerMoyenneActionPerformed
        if ( fichier == null ){ 
            javax.swing.JOptionPane.showMessageDialog( this, "Vous n'avez pas selectionné un nom de fichier " ); 
        }
        else {
            try {
                
                BufferedReader fent;
                fent  = new BufferedReader( new FileReader( fichier ) );

                //ArrayList des variable qu'on cherche à récupérer
                ArrayList notes = new ArrayList();
                ArrayList notes2 = new ArrayList();
                ArrayList nom = new ArrayList();


                double total = 0;
                double total2 = 0;
                double moyenne;
                double moyenne2;
                //sommeCarre permet de calculer l'écart type, c'est la somme des carré de chaque note
                double sommeCarre = 0;
                double sommeCarre2 = 0;
                
                double moyenneCarre;
                double moyenneCarre2;
                double moyenneEtu;
                double moyenneGenerale;
                int i = 0;
                String enr;


                try {
                    while ( ( enr = fent.readLine( ) ) != null ) // null en cas de fin de fichier
                    {
                        //on récupère le nom et les notes de chaque ligne
                        nom.add((enr.substring(0, 19)));
                        notes.add(Double.parseDouble(enr.substring(20,25)));
                        notes2.add(Double.parseDouble(enr.substring(26,31)));

                        //Calcul de la moyenne pour chaque etudiant
                        moyenneEtu = ( (double) notes.get(i) + (double) notes2.get(i))/2;
                        sommeCarre = sommeCarre + ( (double) notes.get(i)* (double) notes.get(i)) ;
                        total = total + (double)notes.get(i);

                        sommeCarre2 = sommeCarre2 + ( (double) notes2.get(i)* (double) notes2.get(i)) ;
                        total2 = total2 + (double)notes2.get(i);
                        //affichage de la ligne
                        listModel.addElement(nom.get(i) + "     " + String.format("%5.2f",notes.get(i)) + "     " + String.format("%5.2f",notes2.get(i))  + "     " + String.format("%5.2f",moyenneEtu));
                        i++;

                    }
                    //Calcul pour les lignes finales
                    moyenne = total/i;
                    moyenneCarre = sommeCarre/i;

                    moyenne2 = total2/i;
                    moyenneCarre2 = sommeCarre2/i;
                    moyenneGenerale = (moyenne + moyenne2)/2;

                    //Affichage des trois lignes finales
                    listModel.addElement(" ");
                    listModel.addElement("Moyenne    =            " + String.format("%5.2f",moyenne)  +"     " + String.format("%5.2f", moyenne2) + "     " + String.format("%5.2f", moyenneGenerale));
                    listModel.addElement("Ecart Type =            " + String.format("%5.2f",Math.sqrt(moyenneCarre-moyenne*moyenne)) + "     " +  String.format("%5.2f",Math.sqrt(moyenneCarre2-moyenne2*moyenne2)));

                } catch (IOException ex) {
                    Logger.getLogger(SelectFich.class.getName()).log(Level.SEVERE, null, ex);
                }
                fent.close( );
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(SelectFich.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SelectFich.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassCastException | StringIndexOutOfBoundsException | NumberFormatException ex){
                javax.swing.JOptionPane.showMessageDialog( this, "Le fichier séléctionné n'est pas conforme" );
            }
        }
    }//GEN-LAST:event_calculerMoyenneActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               new SelectFich().setVisible(true);
        }
     });
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculerMoyenne;
    private javax.swing.JButton editerFichier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectionnerFichier;
    // End of variables declaration//GEN-END:variables
    private javax.swing.DefaultListModel<String> listModel; 
    private String fichierSelectionne = "noms.txt";
    private java.io.File fichier = null;        

}
