package calculette;


/*
 * Calculette.java
 *
 * Created on 21 mars 2007, 08:27
 */

/**
 *
 * @author  Moonesh.Ramburrun
 */
public class Calculette extends javax.swing.JFrame {
    
    /** Creates new form Calculette */
    public Calculette() {
        initComponents();
        op1.selectAll();
        op1.requestFocus();
        setLocation(300,150);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        op1 = new javax.swing.JTextField();
        op2 = new javax.swing.JTextField();
        resul = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addition = new javax.swing.JButton();
        soustraction = new javax.swing.JButton();
        multiplication = new javax.swing.JButton();
        division = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("                                                           C A L C U L E T T E");

        op1.setBackground(new java.awt.Color(0, 255, 255));
        op1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        op1.setText("2");
        op1.setToolTipText("Entrer un nombre réel");
        op1.setNextFocusableComponent(op2);

        op2.setBackground(new java.awt.Color(255, 204, 255));
        op2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        op2.setText("3");
        op2.setToolTipText("Entrer un nombre réel");
        op2.setNextFocusableComponent(addition);

        resul.setEditable(false);
        resul.setBackground(new java.awt.Color(255, 255, 0));
        resul.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        resul.setText("5");
        resul.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Opérande 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("+");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Opérande 2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("=");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Résultat");

        addition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addition.setText("+");
        addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addition(evt);
            }
        });

        soustraction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        soustraction.setText("-");
        soustraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soustraction(evt);
            }
        });

        multiplication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        multiplication.setText("*");
        multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplication(evt);
            }
        });

        division.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        division.setText("/");
        division.setNextFocusableComponent(op1);
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                division(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(27, 27, 27)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(op2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .add(resul)
                            .add(op1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(257, Short.MAX_VALUE)
                        .add(jLabel2)
                        .add(215, 215, 215)))
                .add(addition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(soustraction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(27, 27, 27)
                .add(multiplication, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(division, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(43, 43, 43))
            .add(layout.createSequentialGroup()
                .add(255, 255, 255)
                .add(jLabel4)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(division)
                            .add(multiplication)
                            .add(addition)
                            .add(soustraction))
                        .add(10, 10, 10))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(op1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(11, 11, 11)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(op2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 19, Short.MAX_VALUE)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(resul, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void lireEtValider()
    {
     ok = true;
     try {
        oper1 = Double.parseDouble( op1.getText( ) );
     }catch ( NumberFormatException e ) {
        op1.setText("???");
        resul.setText(" ");
        op1.selectAll();
        op1.requestFocus();
        ok = false;
      }
     try {
        oper2 = Double.parseDouble( op2.getText( ) );
     }catch ( NumberFormatException e ) {
        op2.setText("???");
	resul.setText(" ");
        if (ok) {
	 op2.selectAll();
         op2.requestFocus();
	 ok = false;
        }
     }
   }
    
    /**
     * 
     * @param evt 
     */
    private void division(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_division
     lireEtValider();
     jLabel2.setText( "/" ); 
     if( ok ) {
      resul.setText(String.valueOf(oper1 / oper2));
      op1.selectAll();
      op1.requestFocus();
     }
    }//GEN-LAST:event_division

    /**
     * 
     * @param evt 
     */
    private void multiplication(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplication
     lireEtValider();
     jLabel2.setText( "*" ); 
     if( ok ) {
      resul.setText(String.valueOf(oper1 * oper2));
      op1.selectAll();
      op1.requestFocus();
     }
    }//GEN-LAST:event_multiplication

    /**
     * 
     * @param evt 
     */
    private void soustraction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soustraction
     lireEtValider();
     jLabel2.setText( "-" ); 
     if( ok ) {
      resul.setText(String.valueOf(oper1 - oper2));
      op1.selectAll();
      op1.requestFocus();
     }
    }//GEN-LAST:event_soustraction

    /**
     * 
     * @param evt 
     */
    private void addition(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addition
     lireEtValider();
     jLabel2.setText( "+" ); 
     if( ok ) {
      resul.setText(String.valueOf(oper1 + oper2));
      op1.selectAll();
      op1.requestFocus();
     }
    }//GEN-LAST:event_addition
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
             try
             {
              //  javax.swing.UIManager.setLookAndFeel
              //        ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                // ou ("com.sun.java.swing.plaf.classic.WindowsLookAndFeel");
                // ou ("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                // ou ("com.sun.java.swing.plaf.metal.MetalLookAndFeel");// par défaut
                new Calculette().setVisible(true);
             }catch ( Exception e) { } 
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addition;
    private javax.swing.JButton division;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton multiplication;
    private javax.swing.JTextField op1;
    private javax.swing.JTextField op2;
    private javax.swing.JTextField resul;
    private javax.swing.JButton soustraction;
    // End of variables declaration//GEN-END:variables
    private double  oper1 = 0;
    private double  oper2 = 0;
    private boolean ok = true;
}
