/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listeChainee;

/**
 *
 * @author melou
 */
public class ListeChainee extends javax.swing.JFrame {

    /**
     * Creates new form Tp7gestionlistechainee
     */
    public ListeChainee() {
        initComponents();

        textSaisie.selectAll();
        textSaisie.requestFocus();
        buttonRetDeb.setEnabled(false);
        buttonRetFin.setEnabled(false);
        listechainee = new java.util.LinkedList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textSaisie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textAffichage = new javax.swing.JTextField();
        bouttonInDeb = new javax.swing.JButton();
        buttonInsFin = new javax.swing.JButton();
        buttonRetDeb = new javax.swing.JButton();
        buttonRetFin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liste double chainée");

        jLabel1.setText("Valeur :");

        textSaisie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSaisieActionPerformed(evt);
            }
        });

        jLabel2.setText("Liste Chainée : ");

        textAffichage.setEditable(false);
        textAffichage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAffichageActionPerformed(evt);
            }
        });

        bouttonInDeb.setText("Insérer Au Début");
        bouttonInDeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insererdebut(evt);
            }
        });

        buttonInsFin.setText("Insérer En Fin");
        buttonInsFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insererfin(evt);
            }
        });

        buttonRetDeb.setText("Retirer Au Début");
        buttonRetDeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerdebut(evt);
            }
        });

        buttonRetFin.setText("Retirer En Fin");
        buttonRetFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerfin(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(textSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bouttonInDeb)
                                .addGap(18, 18, 18)
                                .addComponent(buttonInsFin)
                                .addGap(176, 176, 176)
                                .addComponent(buttonRetDeb)
                                .addGap(18, 18, 18)
                                .addComponent(buttonRetFin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(textAffichage)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouttonInDeb)
                    .addComponent(buttonInsFin)
                    .addComponent(buttonRetDeb)
                    .addComponent(buttonRetFin))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSaisieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSaisieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSaisieActionPerformed

    private void textAffichageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAffichageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAffichageActionPerformed

    private void insererdebut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insererdebut

        stringAAfficher = "";
        element = textSaisie.getText();
        if (!element.equals("")) {
            listechainee.addFirst(element);

            for (int i = 0; i < listechainee.size(); i++) {
                
                stringAAfficher = stringAAfficher + listechainee.get(i) + ",";
            }
            textAffichage.setText("[" + stringAAfficher + "]");

            buttonRetDeb.setEnabled(true);
            buttonRetFin.setEnabled(true);
        }
        textSaisie.selectAll();
        textSaisie.requestFocus();

    }//GEN-LAST:event_insererdebut

    private void insererfin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insererfin

        stringAAfficher = "";
        element = textSaisie.getText();
        if (!element.equals("")) {
        listechainee.addLast(element);
        
        //concaténation des éléments à afficher
        for (int i = 0; i < listechainee.size(); i++) {

            stringAAfficher = stringAAfficher + listechainee.get(i) + ",";
        }
        textAffichage.setText("[" + stringAAfficher + "]");

        buttonRetDeb.setEnabled(true);
        buttonRetFin.setEnabled(true);
        }
        textSaisie.selectAll();
        textSaisie.requestFocus();
    }//GEN-LAST:event_insererfin

    private void retirerdebut(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerdebut
        try {
            stringAAfficher = "";

           element=listechainee.removeFirst();
           
           //concaténation des éléments à afficher
            for (int i = 0; i < listechainee.size(); i++) {

                stringAAfficher = stringAAfficher + listechainee.get(i) + ",";
            }
            textAffichage.setText("[" + stringAAfficher + "]");
            //Déactive les bouttons "retirer" si la liste est vide
            if (listechainee.isEmpty()) {
                buttonRetDeb.setEnabled(false);
                buttonRetFin.setEnabled(false);
            }
            
            
        } catch (java.util.NoSuchElementException e) {
            e.getMessage();
        }
         textSaisie.setText(element);
         textSaisie.selectAll();
        textSaisie.requestFocus();
    }//GEN-LAST:event_retirerdebut

    private void retirerfin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerfin
        try {
            stringAAfficher = "";

            element=listechainee.removeLast();
            //concaténation des éléments à afficher
            for (int i = 0; i < listechainee.size(); i++) {

                stringAAfficher = stringAAfficher + listechainee.get(i) + ",";
            }
            textAffichage.setText("[" + stringAAfficher + "]");
            //Déactive les bouttons "retirer" si la liste est vide
            if (listechainee.isEmpty()) {
                buttonRetDeb.setEnabled(false);
                buttonRetFin.setEnabled(false);
            }
        } catch (java.util.NoSuchElementException e) {
            e.getMessage();
        }
        textSaisie.setText(element);
        textSaisie.selectAll();
        textSaisie.requestFocus();
    }//GEN-LAST:event_retirerfin

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeChainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeChainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeChainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeChainee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeChainee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouttonInDeb;
    private javax.swing.JButton buttonInsFin;
    private javax.swing.JButton buttonRetDeb;
    private javax.swing.JButton buttonRetFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textAffichage;
    private javax.swing.JTextField textSaisie;
    // End of variables declaration//GEN-END:variables

    private java.util.LinkedList<String> listechainee;
    private String element = "";
    private String stringAAfficher = "";
}
