/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GenAleatoire;

/**
 *
 * @author p1506898
 */
public class GenAleatoire extends javax.swing.JFrame {

    /**
     * Creates new form GenAleatoire
     */
    public GenAleatoire() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollbarInf = new javax.swing.JScrollBar();
        borneInf = new javax.swing.JLabel();
        borneInfValue = new javax.swing.JLabel();
        borneSup = new javax.swing.JLabel();
        borneSupValue = new javax.swing.JLabel();
        scrollbarSup = new javax.swing.JScrollBar();
        GenAleatLabel = new javax.swing.JLabel();
        aleatValue = new javax.swing.JLabel();
        generer = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollbarInf.setMinimum(1);
        scrollbarInf.setValue(1);
        scrollbarInf.setVisibleAmount(0);
        scrollbarInf.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                ChoixValInf(evt);
            }
        });

        borneInf.setText("Entrer la borne inférieur");

        borneInfValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        borneInfValue.setText("1");

        borneSup.setText("Entrer la borne supérieur");

        borneSupValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        borneSupValue.setText("100");

        scrollbarSup.setValue(100);
        scrollbarSup.setVisibleAmount(0);
        scrollbarSup.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                ChoixValSup(evt);
            }
        });

        GenAleatLabel.setText("Entier aléatoire généré: ");

        aleatValue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aleatValue.setText("???");

        generer.setText("Generer");
        generer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generer(evt);
            }
        });

        exit.setText("Fin");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GenAleatLabel)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(generer)
                            .addComponent(borneInf, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aleatValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borneInfValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(scrollbarInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(borneSup, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borneSupValue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollbarSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(borneInf)
                            .addComponent(borneInfValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(borneSup)
                            .addComponent(borneSupValue)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollbarSup, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollbarInf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenAleatLabel)
                    .addComponent(aleatValue))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generer)
                    .addComponent(exit))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChoixValInf(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_ChoixValInf
        // TODO add your handling code here:
        this.valeurInf = scrollbarInf.getValue();
        borneInfValue.setText(String.valueOf(valeurInf));
    }//GEN-LAST:event_ChoixValInf

    private void ChoixValSup(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_ChoixValSup
        // TODO add your handling code here:
        this.valeurSup = scrollbarSup.getValue();
        borneSupValue.setText(String.valueOf(valeurSup));
    }//GEN-LAST:event_ChoixValSup

    private void generer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generer
        // TODO add your handling code here:
        valeurAleatoire = (int)((valeurSup - valeurInf + 1) * Math.random() + valeurInf);
        aleatValue.setText(String.valueOf(valeurAleatoire));
    }//GEN-LAST:event_generer

    private void exit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_exit

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenAleatoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenAleatoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenAleatoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenAleatoire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenAleatoire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GenAleatLabel;
    private javax.swing.JLabel aleatValue;
    private javax.swing.JLabel borneInf;
    private javax.swing.JLabel borneInfValue;
    private javax.swing.JLabel borneSup;
    private javax.swing.JLabel borneSupValue;
    private javax.swing.JButton exit;
    private javax.swing.JButton generer;
    private javax.swing.JScrollBar scrollbarInf;
    private javax.swing.JScrollBar scrollbarSup;
    // End of variables declaration//GEN-END:variables
    private int valeurInf = 1;
    private int valeurSup = 100;
    private int valeurAleatoire;
            
}
