/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkbox;

/**
 *
 * @author p1506898
 */
public class CheckBox extends javax.swing.JFrame {

    /**
     * Creates new form CheckBox
     */
    public CheckBox() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        choix1 = new javax.swing.JCheckBox();
        choix2 = new javax.swing.JCheckBox();
        choix3 = new javax.swing.JCheckBox();
        fruit_choisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEST DE CHECKBOX");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choix d'un fruit", 0, 0, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        choix1.setBackground(new java.awt.Color(255, 255, 0));
        choix1.setText("Banane");
        choix1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choix1(evt);
            }
        });
        choix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix1ActionPerformed(evt);
            }
        });

        choix2.setBackground(new java.awt.Color(255, 153, 153));
        choix2.setText("Peche");
        choix2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choix2(evt);
            }
        });
        choix2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix2ActionPerformed(evt);
            }
        });

        choix3.setBackground(new java.awt.Color(153, 153, 0));
        choix3.setText("Kiwi");
        choix3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choix3(evt);
            }
        });
        choix3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choix3ActionPerformed(evt);
            }
        });

        fruit_choisi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fruit_choisi.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(choix1)
                        .addGap(18, 18, 18)
                        .addComponent(choix2)
                        .addGap(18, 18, 18)
                        .addComponent(choix3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(fruit_choisi, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choix1)
                    .addComponent(choix2)
                    .addComponent(choix3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(fruit_choisi)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choix1ActionPerformed

    private void choix2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choix2ActionPerformed

    private void choix3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choix3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choix3ActionPerformed

    private void choix1(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choix1
        // TODO add your handling code here:
        if(choix1.isSelected()){
            this.ch1 = choix1.getText();
        } else {
            this.ch1 = "";
        }
        fruit_choisi.setText(ch1 + ' ' + ch2 + ' ' + ch3);
    }//GEN-LAST:event_choix1

    private void choix2(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choix2
        // TODO add your handling code here:
        if(choix2.isSelected()){
            this.ch2 = choix2.getText();
        } else {
            this.ch2 = "";
        }
        fruit_choisi.setText(ch1 + ' ' + ch2 + ' ' + ch3);
    }//GEN-LAST:event_choix2

    private void choix3(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choix3
        // TODO add your handling code here:
        if(choix3.isSelected()){
            this.ch3 = choix3.getText();
        } else {
            this.ch3 = "";
        }
        fruit_choisi.setText(ch1 + ' ' + ch2 + ' ' + ch3);
    }//GEN-LAST:event_choix3

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox choix1;
    private javax.swing.JCheckBox choix2;
    private javax.swing.JCheckBox choix3;
    private javax.swing.JLabel fruit_choisi;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    String ch1 = "", ch2 = "", ch3 = "";
}
