package genaleatoire;

/*
 * GenAleatoire.java
 *
 * Created on 21 mars 2007, 10:09
 */

/**
 *
 * @author  Moonesh.Ramburrun
 */
public class GenAleatoire extends javax.swing.JFrame {
    
    /** Creates new form GenAleatoire */
    public GenAleatoire() {
        initComponents();
        setLocation(200,150);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        generer = new javax.swing.JButton();
        fin = new javax.swing.JButton();
        bInf = new javax.swing.JScrollBar();
        bSup = new javax.swing.JScrollBar();
        borneinf = new javax.swing.JLabel();
        bornesup = new javax.swing.JLabel();
        nbaleat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G é n é r a t i o n   A u t o m a t i q u e  d' u n  E n t  i e r  A l é a t o i r e");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Entrer la borne inférieure : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Entrer la borne supérieure : ");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Entier aléatoire généré : ");

        generer.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        generer.setText("Générer");
        generer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generer(evt);
            }
        });

        fin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        fin.setText("Fin");
        fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fin(evt);
            }
        });

        bInf.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bInf.setMinimum(1);
        bInf.setVisibleAmount(0);
        bInf.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                choixBorneInf(evt);
            }
        });

        bSup.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bSup.setMinimum(1);
        bSup.setValue(100);
        bSup.setVisibleAmount(0);
        bSup.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                choixBorneSup(evt);
            }
        });

        borneinf.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        borneinf.setForeground(new java.awt.Color(102, 102, 255));
        borneinf.setText("1");

        bornesup.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bornesup.setForeground(new java.awt.Color(102, 51, 255));
        bornesup.setText("100");

        nbaleat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nbaleat.setForeground(new java.awt.Color(204, 51, 255));
        nbaleat.setText("14");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 129, Short.MAX_VALUE)
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(40, 40, 40)
                        .add(nbaleat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(346, 346, 346))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(29, 29, 29)
                        .add(borneinf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(bInf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 240, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(bornesup, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(bSup, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(185, 185, 185)
                .add(generer)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(fin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, bSup, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(jLabel1)
                            .add(bornesup)
                            .add(borneinf))
                        .add(38, 38, 38))
                    .add(bInf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(nbaleat))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 124, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(generer)
                    .add(fin))
                .add(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generer
      if ( BSup < BInf )
      {
	 bornesup.setText("???");
	 nbaleat.setText(" ");
      }
      else {
       nbaleat.setText(String.valueOf((int)((BSup-BInf+1)*Math.random()+BInf)));
      }
    }//GEN-LAST:event_generer

    private void fin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fin
      dispose();
      System.exit(0);     
    }//GEN-LAST:event_fin

private void choixBorneInf(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_choixBorneInf
   BInf = bInf.getValue();
   borneinf.setText( String.valueOf( BInf ) );
}//GEN-LAST:event_choixBorneInf

private void choixBorneSup(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_choixBorneSup
   BSup = bSup.getValue();
   bornesup.setText( String.valueOf( BSup ) );    
}//GEN-LAST:event_choixBorneSup
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
             try
             {
                    javax.swing.UIManager.setLookAndFeel
                      ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                // ou ("com.sun.java.swing.plaf.classic.WindowsLookAndFeel");
                // ou ("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                // ou ("com.sun.java.swing.plaf.metal.MetalLookAndFeel");// par défaut
                   new GenAleatoire().setVisible(true);
             }catch ( Exception e ) { };
            }
        });
  
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar bInf;
    private javax.swing.JScrollBar bSup;
    private javax.swing.JLabel borneinf;
    private javax.swing.JLabel bornesup;
    private javax.swing.JButton fin;
    private javax.swing.JButton generer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nbaleat;
    // End of variables declaration//GEN-END:variables
    private int BInf = 1;
    private int BSup = 100;
}
