/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionemp;

/**
 *
 * @author Mooneswar.Ramburrun
 */
import connexion.ConnexionOracleFactory;

public class ConsultEmp extends javax.swing.JFrame {

    /**
     * Creates new form ConsultEmp
     */
    public ConsultEmp() {
        initComponents();
        listModel = new javax.swing.DefaultListModel<>();
        list1.setModel(listModel);
        setLocation(200, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList();
        consultation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("G E S T I O N       D E S       E M P L O Y E S");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText(" empno       ename              job                     mgr             hiredate                 sal                   comm       deptno");

        list1.setBackground(new java.awt.Color(102, 204, 255));
        list1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(list1);

        consultation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        consultation.setText("consultation");
        consultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultation(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(consultation, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultation)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Ouvre une connexion stockée dans la variable connexion
    public void openConnection()  {
        connexion = ConnexionOracleFactory.creerConnexion();
        if (connexion == null) {
            listModel.addElement("Probleme de connection.");
            System.exit(1);
        }
    }

    public void closeConnection() {
      try {
        connexion.close();	// Fermeture de la connexion
      }catch (java.sql.SQLException e){
            System.out.println("ERREUR ORACLE" + e.getMessage());
      }
    }

    private void consultation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultation
        int numero;
        String nom;
        String emploi;
        int numchef;
        String hiredate;
        String sal;
        String comm;
        int numdept;

        listModel.clear();      //listModel.removeAllElements();
        try {
            openConnection();
            java.sql.Statement requete;
            requete = connexion.createStatement();
            java.sql.ResultSet ensresul;
            ensresul = requete.executeQuery(
"select empno,rpad(ename,8),rpad(job,9),nvl(mgr,0),to_char(hiredate,'dd/mm/yyyy'),"
     + "to_char(sal,'9999.99'),to_char(nvl(comm,0),'9990.00'),deptno from emp");
            while (ensresul.next()) {
                numero = ensresul.getInt(1);
                nom = ensresul.getString(2);
                emploi = ensresul.getString(3);
                numchef = ensresul.getInt(4);
                hiredate = ensresul.getString(5);
                sal = ensresul.getString(6);
                comm = ensresul.getString(7);
                numdept = ensresul.getInt(8);

                listModel.addElement(
                        numero
                        + "    "
                        + nom
                        + "    "
                        + emploi
                        + "    "
                        + String.format("%4d", numchef)
                        + "    "
                        + hiredate
                        + "    "
                        + sal
                        + "    "
                        + comm
                        + "    "
                        + numdept);
            }
            ensresul.close();
            requete.close();
            closeConnection();
        } catch (java.sql.SQLException e) {
            listModel.addElement("Erreur execution requete " + e.getMessage());
        }
    }//GEN-LAST:event_consultation

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                //  try
                //   {
                //          javax.swing.UIManager.setLookAndFeel
                //            ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                //         ou ("com.sun.java.swing.plaf.classic.WindowsLookAndFeel");
                //         ou ("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                //         ou ("com.sun.java.swing.plaf.metal.MetalLookAndFeel");// par défaut

                ConsultEmp essai;
                essai = new ConsultEmp();
                essai.setVisible(true);
                //  } catch ( Exception e) { }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.DefaultListModel<String> listModel;
    private java.sql.Connection connexion;
}
