/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nombrepremier;

/**
 *
 * @author p0604667
 */
public class NombrePremier extends javax.swing.JFrame {

    /**
     * Creates new form NombrePremier
     */
    public NombrePremier() {
        initComponents();
        listModel = new javax.swing.DefaultListModel<>();
        jList1.setModel(listModel);
        textQuantite.selectAll();
        textQuantite.requestFocus();
    }
    //Test si n est divible par un nombre compris entre 1 et sqrt(n). Si ce n'est pas le cas, n est premier et la fonction renvoit true.
    public static boolean estPremier(int n) {
	boolean isPremier = true;
	if (n < 0) {
            isPremier = false;
	} else if (n != 0 && n != 1) {
            for (int i = 2; i <= n/2; i++) {
		if (n != i && n % i == 0) {
                    isPremier = false;
                    break;
		}
            }
	}
	return isPremier;
    }
    
    //Permet de s'assurer que l'entrée utilisateur est un nombre et de le caster en double.
    private void lireEtValider()
    {
     ok = true;
     try {
        limite = Integer.parseInt( textQuantite.getText( ) );
     }catch ( NumberFormatException e ) {
        textQuantite.setText("???");
        textQuantite.selectAll();
        textQuantite.requestFocus();
        ok = false;
    }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textQuantite = new javax.swing.JTextField();
        afficher = new javax.swing.JButton();
        fin = new javax.swing.JButton();
        textResult = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quantité:");

        textQuantite.setText(" ");

        afficher.setText("Afficher");
        afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficher(evt);
            }
        });

        fin.setText("Fin");
        fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fin(evt);
            }
        });

        textResult.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(textQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(afficher)
                .addGap(28, 28, 28)
                .addComponent(fin)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textResult)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afficher)
                    .addComponent(fin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textResult, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afficher(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficher
      int i=0;
      int j=0;
      int chiffreTest = 2;
      String maLigne = "";
      lireEtValider();
      listModel.clear();
      if( ok ) {
        while(i < limite)
        {
              if(estPremier(chiffreTest))
              {
                  j++;
                  maLigne = maLigne + String.format("%05d   ", chiffreTest);
                  //On affiche la ligne toute les dix occurences
                  if(j%10 == 0)
                  {
                      listModel.addElement(maLigne);
                      maLigne="";
                  }
                  i++;
              }
              //Ce test permet d'avoir une incrémentation de deux en deux pour éviter de tester les nombres pairs. On gagne du temps d'exécution.
              if (chiffreTest > 2)
              {
                  chiffreTest += 2;
              }
              else
              {
                  chiffreTest++;
              }
              
        }
      }
    }//GEN-LAST:event_afficher

    private void fin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fin
        dispose();
    }//GEN-LAST:event_fin

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NombrePremier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NombrePremier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NombrePremier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NombrePremier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NombrePremier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afficher;
    private javax.swing.JButton fin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JTextField textQuantite;
    private javax.swing.JScrollPane textResult;
    // End of variables declaration//GEN-END:variables
    private int limite;
    private boolean ok;
    private javax.swing.DefaultListModel<String> listModel;
}
